In [1]:
import numpy as np

In [2]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a2.shape

(2, 3)

In [8]:
import pandas as pd

df = pd.DataFrame(a2)   
df

0  1  2
0  1  2  3
1  4  5  6

In [9]:
# create numpy arrays
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [11]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
range_array = np.arange(0, 10, 2)

In [16]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[0, 8, 8, 2, 3],
       [6, 2, 1, 7, 5],
       [7, 0, 2, 2, 2]])

In [18]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.29826581, 0.88266328, 0.60569882],
       [0.0971929 , 0.86735741, 0.22772995],
       [0.08039048, 0.01620733, 0.81735509],
       [0.68228321, 0.10280302, 0.24641723],
       [0.81189468, 0.53170019, 0.29344711]])

In [34]:
# randome seed
np.random.seed(3)
random_array_3 = np.random.randint(10, size=(5, 3))
random_array_3

array([[8, 9, 3],
       [8, 8, 0],
       [5, 3, 9],
       [9, 5, 7],
       [6, 0, 4]])

In [38]:
random_array_3 = np.random.randint(10, size=(5, 3))
random_array_3

array([[2, 2, 7],
       [0, 5, 0],
       [1, 4, 1],
       [2, 2, 4],
       [8, 0, 6]])

In [39]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))

a4

array([[[[0, 4, 1, 5, 1],
         [8, 8, 7, 0, 0],
         [9, 1, 7, 8, 7],
         [4, 0, 0, 4, 3]],

        [[0, 8, 2, 7, 2],
         [1, 3, 2, 4, 1],
         [2, 2, 7, 3, 4],
         [1, 6, 7, 9, 1]],

        [[0, 0, 5, 8, 4],
         [8, 8, 3, 4, 9],
         [2, 5, 4, 7, 9],
         [1, 9, 0, 7, 4]]],


       [[[8, 8, 4, 1, 4],
         [0, 5, 6, 7, 0],
         [7, 8, 1, 5, 3],
         [6, 9, 1, 3, 7]],

        [[4, 9, 0, 8, 4],
         [7, 8, 5, 6, 7],
         [3, 5, 1, 8, 9],
         [2, 9, 8, 9, 4]],

        [[5, 0, 8, 7, 1],
         [2, 5, 2, 7, 6],
         [7, 9, 1, 5, 7],
         [5, 9, 7, 2, 6]]]])

In [40]:
np.random.seed(0)

sales_amounts = np.random.randint(20, size=(5, 3)) 
sales_amounts

# Turn into a DataFrame
weekly_sales = pd.DataFrame(sales_amounts, index=["Mon", "Tues", "Wed", "Thurs", "Fri"], columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [41]:
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [43]:
butters_prices = pd.DataFrame(prices.reshape(1, 3), index=["Price"], columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])
butters_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [47]:
total_sales = prices.dot(sales_amounts.T)   
total_sales

array([240, 138, 458, 232, 142])

# Numpy In Action

<img src="../images/panda.png"/>

In [49]:
from matplotlib.image import imread

panda = imread("../images/panda.png")

SyntaxError: unterminated string literal (detected at line 1) (1786953333.py, line 1)